### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by laurent22** [personalizedrefrigerator/joplin-plugin-revealjs-slides#4]
Not sure if it affects functionalities but I'm getting the below error in the console, while running in dev mode:

```
Uncaught ReferenceError: exports is not defined
    at getRenderedMarkdown.js:1:941
```

which points to this line:

<img width="1169" alt="image" src="https://github.com/personalizedrefrigerator/joplin-plugin-revealjs-slides/assets/1285584/600801d0-73a8-48fe-9473-fa355f73f087">

**Comment by personalizedrefrigerator** [comment]
Thank you for reporting this — the `exports.default` is generated by Webpack from [this file](https://github.com/personalizedrefrigerator/joplin-plugin-revealjs-slides/blob/main/src/contentScripts/getRenderedMarkdown.ts).


# Summary of the problem

I suspect that this is because Webpack is trying to generate CommonJS modules for scripts referenced in `extraScripts`:
https://github.com/personalizedrefrigerator/joplin-plugin-revealjs-slides/blob/744832080b4be46388d346cf38ffe2d143f333f1/webpack.config.js#L265-L267

This script is then loaded as a Markdown-it **asset**, rather than a plugin:
https://github.com/personalizedrefrigerator/joplin-plugin-revealjs-slides/blob/744832080b4be46388d346cf38ffe2d143f333f1/src/contentScripts/markdownIt.ts#L5

The Markdown-it and CodeMirror content scripts probably do not cause this error because:
- For Markdown-it content scripts, we use [shim.requireDynamic](https://github.com/laurent22/joplin/blob/aac8d583729e796c23366972f8dcf71480df01ce/packages/lib/services/plugins/utils/loadContentScripts.ts#L50), which should handle CommonJS modules.
- For CodeMirror 6 content scripts, we [define `exports` before running the plugin script](https://github.com/laurent22/joplin/blob/aac8d583729e796c23366972f8dcf71480df01ce/packages/editor/CodeMirror/pluginApi/PluginLoader.ts#L84). 

I've also noticed this with other plugins that show dialogs with content scripts that have been processed by Webpack (e.g. the Freehand Drawing plugin).

# Possible solutions

- Add `window.exports = {};` to the note viewer and dialog webviews.
- Add support for a new key (e.g. `contentScripts`) to `plugin.config.json`. Extra scripts specified with this key would be generated with a `libraryTarget` that works in an iframe/WebView.

**Comment by personalizedrefrigerator** [comment]
Fixed upstream.
